version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  frontend:
    build: ./user-interface
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - BROWSER=none
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mlapi
      - mongo

  mlapi:
    build: ./backend/ml-api
    container_name: mlapi
    ports:
      - "5001:5001"